ProyectoparqueaderoPS2025/Repos/Proyecto Parqueadero/asp_presentacion/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace asp_presentacion.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

ProyectoparqueaderoPS2025/Repos/Proyecto Parqueadero/asp_presentacion/Pages/Index.cshtml.cs
using libr_dominio.Nucleo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class IndexModel : PageModel
    {
        public bool EstaLogueado = false;
        public string? TipoUsuario { get; set; } // Nuevo campo para el tipo de usuario

        [BindProperty] public string? Email { get; set; }
        [BindProperty] public string? Contrasena { get; set; }

        public void OnGet()
        {
            var variable_session = HttpContext.Session.GetString("Usuario");
            var tipo_usuario_session = HttpContext.Session.GetString("TipoUsuario");

            if (!String.IsNullOrEmpty(variable_session))
            {
                EstaLogueado = true;
                TipoUsuario = tipo_usuario_session;
                return;
            }
        }
        public void OnPostBtClean()
        {
            try
            {
                Email = string.Empty;
                Contrasena = string.Empty;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtEnter()
        {
            try
            {
                if (string.IsNullOrEmpty(Email) || string.IsNullOrEmpty(Contrasena))
                {
                    OnPostBtClean();
                    return;
                }

                string credencialCompleta = Email + "." + Contrasena;
                string tipoUsuario = "";

                // Definir roles según credenciales
                switch (credencialCompleta)
                {
                    case "admin.123":
                        tipoUsuario = "Administrador";
                        break;
                    case "root001.6663":
                    case "root002.9639":
                        tipoUsuario = "Root";
                        break;
                    case "cj001.3693":
                    case "cj002.9999":
                    case "cj003.1266":
                        tipoUsuario = "Cajero";
                        break;
                    default:
                        OnPostBtClean();
                        return;
                }

                // Guardar en sesión
                HttpContext.Session.SetString("Usuario", Email!);
                HttpContext.Session.SetString("TipoUsuario", tipoUsuario);

                ViewData["Logged"] = true;
                EstaLogueado = true;
                TipoUsuario = tipoUsuario;
                OnPostBtClean();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtClose()
        {
            try
            {
                HttpContext.Session.Clear();
                HttpContext.Response.Redirect("/");
                EstaLogueado = false;
                TipoUsuario = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }


}

ProyectoparqueaderoPS2025/Repos/Proyecto Parqueadero/asp_presentacion/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Index";
    ViewData["ContainerClass"] = "container-login-bg";
}
@if (!Model.EstaLogueado)
{
    <div class="container"
         align="left"
         style="width:100%">
        <h3>
            Login
        </h3>

        <form method="POST">
            <div style="width:60%">
                <div class="form-group">
                    <label class="control-label">
                        Usuario (Referencia de contrato):
                    </label>
                    <input onchange="keyUp(this)"
                           asp-for="@Model.Email"
                           class="form-control" />
                </div>
                <div class="form-group">
                    <label class="control-label">
                        Contrasena (Cedula):
                    </label>
                    <input type="password"
                           onchange="keyUp(this)"
                           asp-for="@Model.Contrasena"
                           class="form-control" />
                </div>

                <input type="submit"
                       value="Limpiar"
                       asp-page-handler="BtClean"
                       class="btn btn-default" />
                <input type="submit"
                       value="Entrar"
                       asp-page-handler="BtEnter"
                       class="btn btn-default" />
            </div>
        </form>
    </div>
}
else
{
    <div class="container"
         align="center">
        <h1 class="display-4">
            Bienvenido
        </h1>

        <form method="POST">
            <input type="submit"
                   value="Cerrar"
                   asp-page-handler="BtClose"
                   class="btn btn-default" />
        </form>
    </div>
}