ProyectoparqueaderoPS2025/Repos/Proyecto Parqueadero/asp_presentacion/Pages/Ventanas/Auditorias.cshtml.cs
using libr_dominio.Entidades;
using libr_dominio.Nucleo;
using libr_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class AuditoriasModel : PageModel
    {
        private IAuditoriasPresentacion? iPresentacion = null;  //Clase principal
        //Clases asociada 


        //Las clases asociadas tambien se mandan como parametros en el contructor
        public AuditoriasModel(IAuditoriasPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Auditorias();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Auditorias? Actual { get; set; }
        [BindProperty] public Auditorias? Filtro { get; set; }
        [BindProperty] public List<Auditorias>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("Usuario");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.TipoModificacion = Filtro!.TipoModificacion ?? "";

                Accion = Enumerables.Ventanas.Listas;

                var task = this.iPresentacion!.PorTipoModificacion(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
        
        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

ProyectoparqueaderoPS2025/Repos/Proyecto Parqueadero/asp_presentacion/Pages/Ventanas/Cargos.cshtml.cs
using libr_dominio.Entidades;
using libr_dominio.Nucleo;
using libr_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class CargosModel : PageModel
    {
        private ICargosPresentacion? iPresentacion = null;

        public CargosModel(ICargosPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Cargos();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Cargos? Actual { get; set; }
        [BindProperty] public Cargos? Filtro { get; set; }
        [BindProperty] public List<Cargos>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("Usuario");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.Cargo = Filtro!.Cargo ?? "";

                Accion = Enumerables.Ventanas.Listas;

                var task = this.iPresentacion!.PorCargo(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Cargos();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;

                Task<Cargos>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

ProyectoparqueaderoPS2025/Repos/Proyecto Parqueadero/asp_presentacion/Pages/Ventanas/Clientes.cshtml.cs
using libr_dominio.Entidades;
using libr_dominio.Nucleo;
using libr_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class ClientesModel : PageModel
    {
        private IClientesPresentacion? iPresentacion = null;
        private ITipoClientesPresentacion? iTipoClientesPresentacion = null;
        private IVehiculosPresentacion? iVehiculosPresentacion = null;

        public ClientesModel(IClientesPresentacion iPresentacion,
            ITipoClientesPresentacion iTipoClientesPresentacion,
            IVehiculosPresentacion? iVehiculosPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                this.iTipoClientesPresentacion = iTipoClientesPresentacion;
                this.iVehiculosPresentacion = iVehiculosPresentacion;
                Filtro = new Clientes();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Clientes? Actual { get; set; }
        [BindProperty] public Clientes? Filtro { get; set; }
        [BindProperty] public List<Clientes>? Lista { get; set; }
        [BindProperty] public List<TipoClientes>? TipoClientes { get; set; }
        [BindProperty] public List<Vehiculos>? Vehiculos { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("Usuario");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.Cedula = Filtro!.Cedula ?? "";

                Accion = Enumerables.Ventanas.Listas;

                var task = this.iPresentacion!.PorCedula(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        private void CargarCombox()
        {
            try
            {
                var task = this.iTipoClientesPresentacion!.Listar();
                task.Wait();
                TipoClientes = task.Result;

                var task2 = this.iVehiculosPresentacion!.Listar();
                task2.Wait();
                Vehiculos = task2.Result;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Clientes();
                CargarCombox();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                CargarCombox();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;

                Task<Clientes>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

ProyectoparqueaderoPS2025/Repos/Proyecto Parqueadero/asp_presentacion/Pages/Ventanas/Cargos.cshtml
@page
@model asp_presentacion.Pages.Ventanas.CargosModel
@{
    ViewData["Titulo"] = "Cargos";
}
<center>
    <div>
        <form method="POST"
              enctype="multipart/form-data">
            @Html.AntiForgeryToken()

            <div align="left">
                <h3>Cargos</h3>
            </div>
            <div align="left"
                 class="bt_panel_buttons">
                <input type="submit"
                       value="Refrescar"
                       asp-page-handler="BtRefrescar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != libr_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Nuevo"
                       asp-page-handler="BtNuevo"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != libr_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Guardar"
                       asp-page-handler="BtGuardar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Cancelar"
                       asp-page-handler="BtCancelar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
            </div>

            @if (Model.Accion != libr_dominio.Nucleo.Enumerables.Ventanas.Listas ||
            Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Id" />
            }
            @if (Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Cargo" />
            }

            @if (Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Editar)
            {
                <div class="containers_vn panel panel-default">
                    <h3>Cargo</h3>

                    <div>

                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Nombre del cargo 
                            </label>
                            <div class="col-lg-6">
                                <input id="Nombre del cargo"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Cargo" />
                            </div>
                        </div>

                    </div>
                </div>
            }

            @if (ViewData.ContainsKey("Mensaje"))
            {
                <input type="hidden"
                       asp-for="@Model.Accion" />
                @await Html.PartialAsync("../Emergentes/Mensajes.cshtml")
                ;
            }

            @if (Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">
                                Mensaje
                            </h2>

                            <h4 align="left">
                                Desea borrar la entidad?
                            </h4>
                            <h6 align="left">
                                @Model.Actual!.Cargo
                            </h6>
                            <br />
                            <br />
                            <input type="submit"
                                   value="Borrar"
                                   asp-page-handler="BtBorrar"
                                   class="btn btn-secondary" />
                            <input type="submit"
                                   value="Cerrar"
                                   asp-page-handler="BtCancelar"
                                   class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Listas ||
            Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input id="flCargo"
                       class="cts_forms form-control"
                       asp-for="@Model.Filtro!.Cargo"
                       placeholder="Buscar por cargo" />
                <br />

                <div class="containers_vn panel panel-default">
                    <table class="tb_data table table-striped table-bordered table-hover">
                        <tr>
                            <th>
                                Cargos
                            </th>
                        </tr>
                        @if (Model != null && Model.Lista != null)
                        {
                            @foreach (var elemento in Model.Lista)
                            {
                                <tr>
                                    <td>
                                        @elemento.Cargo
                                    </td>
                                    <td>
                                        <input type="submit"
                                               value="Modificar"
                                               asp-page-handler="BtModificar"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                        <input type="submit"
                                               value="Borrar"
                                               asp-page-handler="BtBorrarVal"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            }
        </form>
    </div>
</center>

ProyectoparqueaderoPS2025/Repos/Proyecto Parqueadero/asp_presentacion/Pages/Ventanas/Clientes.cshtml
@page
@model asp_presentacion.Pages.Ventanas.ClientesModel
@{
    ViewData["Titulo"] = "Clientes";
}
<center>
    <div>
        <form method="POST"
              enctype="multipart/form-data">
            @Html.AntiForgeryToken()

            <div align="left">
                <h3>Clientes</h3>
            </div>
            <div align="left"
                 class="bt_panel_buttons">
                <input type="submit"
                       value="Refrescar"
                       asp-page-handler="BtRefrescar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion !=libr_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Nuevo"
                       asp-page-handler="BtNuevo"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion !=libr_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Guardar"
                       asp-page-handler="BtGuardar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion ==libr_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Cancelar"
                       asp-page-handler="BtCancelar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion ==libr_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
            </div>

            @if (Model.Accion != libr_dominio.Nucleo.Enumerables.Ventanas.Listas ||
            Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Id" />
            }
            @if (Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Cedula" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Nombre" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Vehiculo" />
                <input type="hidden"
                       asp-for="@Model.Actual!.TipoCliente" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Codigo" />
            }

            @if (Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Editar)
            {
                <div class="containers_vn panel panel-default">
                    <h3>Cliente</h3>

                    <div>

                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Cedula
                            </label>
                            <div class="col-lg-6">
                                <input id="nmCedula"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Cedula" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Nombre
                            </label>
                            <div class="col-lg-6">
                                <input id="nmNombre"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Nombre" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Vehiculo
                            </label>
                            <div class="col-lg-6">
                                <select id="nmVehiculo"
                                        class="form-control"
                                        asp-for="@Model.Actual!.Vehiculo"
                                        asp-items="@(new SelectList(Model.Vehiculos, "Id", "Placa"))">
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Tipo de cliente 
                            </label>
                            <div class="col-lg-6">
                                <select id="nmTipoCliente"
                                        class="form-control"
                                        asp-for="@Model.Actual!.TipoCliente"
                                        asp-items="@(new SelectList(Model.TipoClientes, "Id", "TipoCliente"))">
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Codigo
                            </label>
                            <div class="col-lg-6">
                                <input id="nmNombre"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Nombre" />
                            </div>
                        </div>

                    </div>
                </div>
            }

            @if (ViewData.ContainsKey("Mensaje"))
            {
                <input type="hidden"
                       asp-for="@Model.Accion" />
                @await Html.PartialAsync("../Emergentes/Mensajes.cshtml")
                ;
            }

            @if (Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">
                                Mensaje
                            </h2>

                            <h4 align="left">
                                Desea borrar la entidad?
                            </h4>
                            <h6 align="left">
                                @Model.Actual!.Cedula, @Model.Actual!.Nombre
                            </h6>
                            <br />
                            <br />
                            <input type="submit"
                                   value="Borrar"
                                   asp-page-handler="BtBorrar"
                                   class="btn btn-secondary" />
                            <input type="submit"
                                   value="Cerrar"
                                   asp-page-handler="BtCancelar"
                                   class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Listas ||
            Model.Accion == libr_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input id="flPlaca"
                       class="cts_forms form-control"
                       asp-for="@Model.Filtro!.Cedula"
                       placeholder="Filtrar por cedula" />
                <br />

                <div class="containers_vn panel panel-default">
                    <table class="tb_data table table-striped table-bordered table-hover">
                        <tr>
                            <th>
                                Cedula
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th class="cl_actions">
                                Vehiculo
                            </th>
                            <th class="cl_actions">
                                Tipo de cliente
                            </th>
                            <th>
                                Codigo
                            </th>
                            <th>
                                Modificar
                            </th>
                        </tr>
                        @if (Model != null && Model.Lista != null)
                        {
                            @foreach (var elemento in Model.Lista)
                            {
                                <tr>
                                    <td>
                                        @elemento.Cedula
                                    </td>
                                    <td>
                                        @elemento.Nombre
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento._Vehiculo!.Placa
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento._TipoCliente!.TipoCliente
                                    </td>
                                    <td>
                                        @elemento.Codigo
                                    </td>
                                    <td>
                                        <input type="submit"
                                               value="Modificar"
                                               asp-page-handler="BtModificar"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                        <input type="submit"
                                               value="Borrar"
                                               asp-page-handler="BtBorrarVal"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            }
        </form>
    </div>
</center>